Test de l'algorithme P3P avec opencv et numpy 

Test de P3P version open CV : 
- affichage des matrices de rotation et de translation générée initialement (correspondant à celle du papier de Kneip)
- puis des solutions générées par l'algorithme opencv 
- ansi que des erreurs (distance euclidienne) entre les points initiaux et les points retrouvés à partir des matrices retrouvées par P3P

In [1]:
%run test_openCV.py 

R = 
 [[ 1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
T = 
 [[0]
 [0]
 [6]]
------------ Solution n° :  1 ----------------
R = 
 [[ 1.0000000e+00  0.0000000e+00 -0.0000000e+00]
 [-0.0000000e+00 -1.0000000e+00 -1.2246468e-16]
 [ 0.0000000e+00  1.2246468e-16 -1.0000000e+00]]
T = 
 [[-1.33232314e-12]
 [ 1.56141766e-12]
 [ 6.00000000e+00]]
erreur_pt 0  =  7.24450534529106e-12
erreur_pt 1  =  9.784969542309688e-12
erreur_pt 2  =  3.1956342184544215e-11
erreur_pt 3  =  2.348549048809458e-11
------------ Solution n° :  2 ----------------
R = 
 [[ 0.86336438 -0.16045879 -0.47838785]
 [ 0.48164725  0.54465656  0.68656038]
 [ 0.15039243 -0.82316597  0.54752161]]
T = 
 [[-0.22862136]
 [ 2.17220401]
 [ 4.62098862]]
erreur_pt 0  =  3.346997642614819e-11
erreur_pt 1  =  1.1506392390986726e-11
erreur_pt 2  =  2.2120334588466035e-11
erreur_pt 3  =  24.184228750570135

------------ Best solution : ----------------
Solution n° : 1 

R estimé = 
 [[ 1.0000000e+00  0.0000000e+00 -0.0000000e+00]
 [-0.0000000e+00 -1.0

Test des fonctions de résolutions de racines des polynomes de degré 3 et 4 : 
- affichage des coeffiçiants (générés aléatoirement) du polynome
- puis des racines trouvées pas l'algorithme
- calcul du polynome appliqué à chaque racine 
- vérificiation que le polynome appliqué à la racine a bien une valeur proche de zéro (à  10^(-10) près )

In [2]:
%run test_resolution_polynomes.py

---- Begin of test_polynomial_root_calculation_3rd_degree ----
f(x) =  16.614251223605628 *x**3 +  17.579476733538087 *x**2 +  -2.762173729807415 *x +  19.748978488109344
Roots : [-1.61609443-0.j          0.27899909+0.81097718j  0.27899909-0.81097718j] 

f(r) =  (1.0658141036401503e-14+0j) 

f(r) =  (-1.4210854715202004e-14-3.4638958368304884e-14j) 

f(r) =  (-2.4868995751603507e-14-3.9968028886505635e-15j) 

Values lower in norm than 10^(-10) :  True 

---- Begin of test_polynomial_root_calculation_4th_degree_ferrari ----
f(x) =  -3.2723963857540994 *x**4 +  -17.98901436481621 *x**3 +  7.082102813144523 *x**2 +  -11.173585160355444 *x +  11.766915429940418
Roots : [-0.11951949+0.91046411j -0.11951949-0.91046411j  0.71403102+0.j
 -5.97219111-0.j        ] 

f(r) =  (1.7763568394002505e-15+3.552713678800501e-15j) 

f(r) =  (1.7763568394002505e-15-3.552713678800501e-15j) 

f(r) =  (3.552713678800501e-15+0j) 

f(r) =  (-1.9184653865522705e-13+0j) 

Values lower in norm than 10^(-10) :  Tru

Test de P3P version numpy : 
- affichage des matrices de rotation et de translation générée initialement (correspondant à celle du papier de Kneip)
- calcul des features vectors (fi = TPi / ||TP|| ) avec T matrice de translation de la caméra et Pi les points utilisés pour la résolution de P3P
- puis des solutions générées par l'algorithme P3P_numpy 
- ansi que des erreurs (distance euclidienne) entre les points initiaux et les points retrouvés à partir des matrices retrouvées par P3P

In [3]:
%run test_numpy.py

R = 
 [[ 1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
T = 
 [[0]
 [0]
 [6]]
features vectors = 
 [[-0.07939407  0.10438052 -0.53004309]
 [-0.1215374  -0.06193074 -0.57322427]
 [ 0.04934058  0.0564917  -0.67884883]]
------------ Solution n° :  1 ----------------
R = 
 [[-0.57104868  0.52839779  0.10056391]
 [-0.34371081 -0.10931269  0.53331802]
 [ 0.71073291  0.18469544  0.16464107]]
T = 
 [[-1.27792837]
 [ 3.70669826]
 [ 1.81781513]]
erreur_pt 0  =  116.85777397679166
erreur_pt 1  =  513.7445639433797
erreur_pt 2  =  71.11516647269359
erreur_pt 3  =  84.4429316787973
------------ Solution n° :  2 ----------------
R = 
 [[-0.91092191  0.05941308 -0.06702242]
 [-0.05546337  0.54927462 -0.09003696]
 [ 0.34135038 -0.14153929 -0.55592197]]
T = 
 [[-3.06888072]
 [-1.10108156]
 [-4.41840232]]
erreur_pt 0  =  37.677462656533265
erreur_pt 1  =  37.239916693213324
erreur_pt 2  =  54.78299643752006
erreur_pt 3  =  38.54136332599207

------------ Best solution : ----------------
Solution n° : 2 

R estimé = 

Pour la méthode P3P pour l'instant valeurs d'erreurs très élevées - pb dans la résolution de P3P à chercher 

Affichage des matrices de rotation et de potition trouvée par l'algo open cv et l'algo numpy 

In [4]:
%run test_comparaison

R = 
 [[ 1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
T = 
 [[0]
 [0]
 [6]]
features vectors = 
 [[ 0.00421989  0.0250702  -0.49555492]
 [ 0.10007844  0.05051166 -0.63397391]
 [-0.01766522  0.13999813 -0.60264213]]
--------- Solutions : --------------------- 
Solution open CV : 
 [[[ 3.71561615e-10  1.00000000e+00  0.00000000e+00 -0.00000000e+00]
  [-4.52938687e-10 -0.00000000e+00 -1.00000000e+00 -1.22464680e-16]
  [ 6.00000000e+00  0.00000000e+00  1.22464680e-16 -1.00000000e+00]]

 [[ 9.32057948e-01  2.49487564e-01 -7.69075959e-01 -5.88454013e-01]
  [-1.03642678e+00  8.01288980e-01 -1.77273961e-01  5.71410459e-01]
  [ 6.92089453e+00 -5.43775620e-01 -6.14081519e-01  5.72024442e-01]]

 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.000000