Test de l'algorithme P3P avec opencv et numpy 

Test de P3P version open CV : 
- affichage des matrices de rotation et de translation générée initialement (correspondant à celle du papier de Kneip)
- puis des solutions générées par l'algorithme opencv 
- ansi que des erreurs (distance euclidienne) entre les points initiaux et les points retrouvés à partir des matrices retrouvées par P3P

In [18]:
%run test_openCV.py 

R = 
 [[ 1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
T = 
 [[0]
 [0]
 [6]]
------------ Solution n° :  1 ----------------
R = 
 [[ 1.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00 -1.0000000e+00 -1.2246468e-16]
 [ 0.0000000e+00  1.2246468e-16 -1.0000000e+00]]
T = 
 [[-3.50820151e-10]
 [-2.28022046e-11]
 [ 6.00000000e+00]]
erreur_pt 0  =  1.7894137967863079e-09
erreur_pt 1  =  4.64876749890262e-09
erreur_pt 2  =  3.3089417283457984e-09
erreur_pt 3  =  1.347280091063442e-09
------------ Solution n° :  2 ----------------
R = 
 [[ 0.74977217 -0.63946142 -0.17009055]
 [ 0.39383199  0.22469409  0.89129621]
 [-0.53173119 -0.73525619  0.42030973]]
T = 
 [[ 0.69136646]
 [-1.79025506]
 [ 6.24181107]]
erreur_pt 0  =  2.0019817813980848e-09
erreur_pt 1  =  1.2260465193754163e-09
erreur_pt 2  =  1.6324339518546964e-09
erreur_pt 3  =  17.106636591017885


Test des fonctions de résolutions de racines des polynomes de degré 3 et 4 : 
- affichage des coeffiçiants (générés aléatoirement) du polynome
- puis des racines trouvées pas l'algorithme
- calcul du polynome appliqué à chaque racine 
- vérificiation que le polynome appliqué à la racine a bien une valeur proche de zéro (à  10^(-10) près )

In [19]:
%run test_resolution_polynomes.py

---- Begin of test_polynomial_root_calculation_3rd_degree ----
f(x) =  -6.542744728628165 *x**3 +  18.01899788992803 *x**2 +  -2.3384067212921877 *x +  -17.89945687531036
Roots : [-0.82570924-0.j          1.78987593+0.33103306j  1.78987593-0.33103306j] 

f(r) =  0j 

f(r) =  (1.0658141036401503e-14+1.0436096431476471e-14j) 

f(r) =  (7.105427357601002e-15+7.327471962526033e-15j) 

Values lower in norm than 10^(-10) :  True 

---- Begin of test_polynomial_root_calculation_4th_degree_ferrari ----
f(x) =  -17.031268896855867 *x**4 +  0.29391348039503384 *x**3 +  17.093448869619117 *x**2 +  -1.361187832932778 *x +  -11.074988542660131
Roots : [ 0.81325798+0.41776994j  0.81325798-0.41776994j -0.80462934+0.36122755j
 -0.80462934-0.36122755j] 

f(r) =  (-7.105427357601002e-15+3.3306690738754696e-16j) 

f(r) =  (-7.105427357601002e-15-3.3306690738754696e-16j) 

f(r) =  (-5.329070518200751e-15-3.3861802251067274e-15j) 

f(r) =  (-5.329070518200751e-15+3.3861802251067274e-15j) 

Values lower in 

Test de P3P version numpy : 
- affichage des matrices de rotation et de translation générée initialement (correspondant à celle du papier de Kneip)
- calcul des features vectors (fi = TPi / ||TP|| ) avec T matrice de translation de la caméra et Pi les points utilisés pour la résolution de P3P
- puis des solutions générées par l'algorithme P3P_numpy 
- ansi que des erreurs (distance euclidienne) entre les points initiaux et les points retrouvés à partir des matrices retrouvées par P3P

In [20]:
%run test_numpy.py

R = 
 [[ 1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
T = 
 [[0]
 [0]
 [6]]
features vectors = 
 [[-0.07363515 -0.08217048 -0.59713374]
 [ 0.084291    0.19354298 -0.57320041]
 [ 0.1714294   0.0096822  -0.6972817 ]]
------------ Solution n° :  1 ----------------
R = 
 [[-0.83513792  0.33672181  0.26944486]
 [-0.12938097 -0.61508449 -0.03748883]
 [ 0.36305545 -0.18560466  0.54779152]]
T = 
 [[2.2062749 ]
 [1.08089318]
 [4.5660049 ]]
erreur_pt 0  =  48.17082621276599
erreur_pt 1  =  23.551849792498206
erreur_pt 2  =  15.679386027897406
erreur_pt 3  =  55.80887736958333
------------ Solution n° :  2 ----------------
R = 
 [[-0.89791972  0.24365548 -0.10463413]
 [ 0.18155897  0.03284666 -0.59674561]
 [ 0.08234418 -0.68243147 -0.08383242]]
T = 
 [[-1.34074395]
 [-5.50730682]
 [-0.81890959]]
erreur_pt 0  =  8829.670642215518
erreur_pt 1  =  135.4773949120523
erreur_pt 2  =  398.84824249906194
erreur_pt 3  =  516.0625726452305


Pour la méthode P3P pour l'instant valeurs d'erreurs très élevées - pb dans la résolution de P3P à chercher 

Affichage des matrices de rotation et de potition trouvée par l'algo open cv et l'algo numpy 

In [21]:
%run test_comparaison

R = 
 [[ 1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
T = 
 [[0]
 [0]
 [6]]
features vectors = 
 [[-0.12666154  0.19254873 -0.41764781]
 [ 0.165314    0.15085441 -0.51701275]
 [-0.04391728  0.10914631 -0.67164034]]
--------- Solutions : --------------------- 
Solution open CV : 
 [[[ 1.07136522e-14  1.00000000e+00 -0.00000000e+00  0.00000000e+00]
  [ 1.77635684e-15  0.00000000e+00 -1.00000000e+00 -1.22464680e-16]
  [ 6.00000000e+00  0.00000000e+00  1.22464680e-16 -1.00000000e+00]]

 [[ 8.83641151e-01  8.81345208e-01 -4.69520841e-01 -5.27333336e-02]
  [-1.99161553e+00  3.66256309e-01  7.49449365e-01 -5.51526939e-01]
  [ 2.23919402e+00  2.98474356e-01  4.66771709e-01  8.32488577e-01]]

 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.000000