Test de l'algorithme P3P avec opencv et numpy 

Test de P3P version open CV : 
- affichage des matrices de rotation et de translation générée initialement (correspondant à celle du papier de Kneip)
- puis des solutions générées par l'algorithme opencv 
- ansi que des erreurs (distance euclidienne) entre les points initiaux et les points retrouvés à partir des matrices retrouvées par P3P

In [1]:
%run test_openCV.py 

R = 
 [[ 1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
T = 
 [[0]
 [0]
 [6]]
------------ Solution n° :  1 ----------------
R = 
 [[ 1.0000000e+00 -0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00 -1.0000000e+00 -1.2246468e-16]
 [ 0.0000000e+00  1.2246468e-16 -1.0000000e+00]]
T = 
 [[7.08655357e-13]
 [3.63542529e-13]
 [6.00000000e+00]]
erreur_pt 0  =  1.810859921846042e-11
erreur_pt 1  =  4.818510360754164e-12
erreur_pt 2  =  7.395834821850691e-12
erreur_pt 3  =  3.048653665785706e-12
------------ Solution n° :  2 ----------------
R = 
 [[-0.86428499  0.0542953   0.50006348]
 [ 0.13308775 -0.93404319  0.33143772]
 [ 0.4850764   0.35300897  0.80005347]]
T = 
 [[ 1.16376725]
 [-0.58389455]
 [ 3.00125862]]
erreur_pt 0  =  3.528789531849031e-12
erreur_pt 1  =  4.594352688068417e-12
erreur_pt 2  =  5.3326744158000054e-12
erreur_pt 3  =  15.899086551182474

------------ Best solution : ----------------
Solution n° : 1 

R estimé =  [[-0.86428499  0.0542953   0.50006348]
 [ 0.13308775 -0.93404319  0.331437

Test des fonctions de résolutions de racines des polynomes de degré 3 et 4 : 
- affichage des coeffiçiants (générés aléatoirement) du polynome
- puis des racines trouvées pas l'algorithme
- calcul du polynome appliqué à chaque racine 
- vérificiation que le polynome appliqué à la racine a bien une valeur proche de zéro (à  10^(-10) près )

In [2]:
%run test_resolution_polynomes.py

---- Begin of test_polynomial_root_calculation_3rd_degree ----
f(x) =  -17.97121111600312 *x**3 +  -8.58950962829741 *x**2 +  14.96894294854797 *x +  -12.847443187926375
Roots : [-1.41951636-0.j         0.47077847+0.5310207j  0.47077847-0.5310207j] 

f(r) =  (-5.329070518200751e-15+0j) 

f(r) =  (-3.552713678800501e-15+8.881784197001252e-15j) 

f(r) =  (-5.329070518200751e-15+1.509903313490213e-14j) 

Values lower in norm than 10^(-10) :  True 

---- Begin of test_polynomial_root_calculation_4th_degree_ferrari ----
f(x) =  18.409208408946746 *x**4 +  3.9257138437698913 *x**3 +  0.5269504569643217 *x**2 +  -13.002078972528341 *x +  -13.042357691913327
Roots : [ 1.04050765+0.j         -0.71787905+0.j         -0.26793794+0.93631249j
 -0.26793794-0.93631249j] 

f(r) =  (-8.881784197001252e-15+0j) 

f(r) =  (-1.4210854715202004e-14+0j) 

f(r) =  (-1.2434497875801753e-14+0j) 

f(r) =  (-1.2434497875801753e-14+0j) 

Values lower in norm than 10^(-10) :  True 



Test de P3P version numpy : 
- affichage des matrices de rotation et de translation générée initialement (correspondant à celle du papier de Kneip)
- calcul des features vectors (fi = TPi / ||TP|| ) avec T matrice de translation de la caméra et Pi les points utilisés pour la résolution de P3P
- puis des solutions générées par l'algorithme P3P_numpy 
- ansi que des erreurs (distance euclidienne) entre les points initiaux et les points retrouvés à partir des matrices retrouvées par P3P

In [3]:
%run test_numpy.py

R = 
 [[ 1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
T = 
 [[0]
 [0]
 [6]]
features vectors = 
 [[ 0.13415588  0.07019628 -0.62886368]
 [-0.06786469  0.14452995 -0.48801804]
 [ 0.05129853 -0.13577486 -0.58393552]]
------------ Solution n° :  1 ----------------
R = 
 [[-0.19362516 -0.29772902 -0.64990743]
 [-0.24382212 -0.87476287  0.11399482]
 [-0.6647586   0.06155529  0.07021091]]
T = 
 [[-1.95803255]
 [ 2.15178474]
 [ 1.16220207]]
erreur_pt 0  =  445.6873973797423
erreur_pt 1  =  102.09279972868153
erreur_pt 2  =  241.6976031321923
erreur_pt 3  =  218.13261286891822
------------ Solution n° :  2 ----------------
R = 
 [[ 0.44434658 -0.49412953 -0.11369193]
 [-0.57374497 -0.72784974 -0.29041745]
 [ 0.11052941  0.28933107 -0.58569267]]
T = 
 [[ 0.07192721]
 [-0.01386939]
 [-5.03917717]]
erreur_pt 0  =  22.44802664265796
erreur_pt 1  =  27.916024632521584
erreur_pt 2  =  28.03645888711508
erreur_pt 3  =  13.052873247395214

------------ Best solution : ----------------
Solution n° : 0 

R estimé 

Pour la méthode P3P pour l'instant valeurs d'erreurs très élevées - pb dans la résolution de P3P à chercher 

Affichage des matrices de rotation et de potition trouvée par l'algo open cv et l'algo numpy 

In [4]:
%run test_comparaison

R = 
 [[ 1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
T = 
 [[0]
 [0]
 [6]]
features vectors = 
 [[-0.14797776  0.13931927 -0.45033839]
 [-0.15724004  0.12207411 -0.5007142 ]
 [ 0.12100459 -0.1191205  -0.48181234]]
--------- Solutions : --------------------- 
Solution open CV : 
 [[[ 9.42879108e-12  1.00000000e+00  0.00000000e+00 -0.00000000e+00]
  [ 4.21895852e-12 -0.00000000e+00 -1.00000000e+00 -1.22464680e-16]
  [ 6.00000000e+00  0.00000000e+00  1.22464680e-16 -1.00000000e+00]]

 [[ 3.92533648e-01 -1.16749327e-01 -9.84159675e-01 -1.33414123e-01]
  [ 1.00352723e+00  7.57135264e-01 -1.26131306e-03 -6.53256919e-01]
  [ 3.54298636e+00  6.42740840e-01 -1.77279842e-01  7.45289253e-01]]

 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.000000